### ISSUE TITLE
OpenURL - not displaying the (ETH) openURL ill component with the Central Package

### ISSUE THREAD

**Issue by mehmetc** [mehmetc/41SLSP_NETWORK#6]
http://localhost:8003/discovery/openurl?institution=41SLSP_RZS&vid=41SLSP_RZS:VU07&volume=&date=20190101&issn=13542990&issue=91&genre=article&spage=74&pid=%3Cauthors%3EHowarth,%20Crispin%3C%2Fauthors%3E%3Cui%3EXRAI19E0304Z-1237%3C%2Fui%3E%3Cdate%3E20190101%3C%2Fdate%3E%3Cdb%3Eant%3C%2Fdb%3E&title=Tribal%20art&atitle=From%20the%20chisel%20of%20Mataora:%20the%20M%C4%81ori%20art%20of%20skin%20marking&sid=EBSCO:ant

**Comment by phlowZHB** [comment]
For testing the URL should work: http://localhost:8003/discovery/openurl?institution=41SLSP_RZS&vid=41SLSP_RZS:VU07

**Comment by mehmetc** [comment]
see if it is possible to change the html template

**Comment by mehmetc** [comment]
new html can be injected during compile
